name: sliding_crossword
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: 6.0.2
  equatable: 2.0.3
  google_fonts: 2.2.0
  json_annotation: 4.4.0
  auto_size_text: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: 6.1.4
  flutter_lints: 1.0.0
  build_runner: 2.1.7

flutter:
  uses-material-design: true
