name: sliding_crossword
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: 6.0.2
  equatable: 2.0.3
  json_annotation: 4.4.0
  auto_size_text: 3.0.0
  flutter_svg: 1.0.3
  shared_preferences: 2.0.12
  firebase_core: 1.11.0
  firebase_auth: 3.3.5
  google_sign_in: 5.2.3
  go_router: 3.0.1
  cloud_firestore: 3.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: 6.1.4
  flutter_lints: 1.0.0
  build_runner: 2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
